name: Check Code Quality

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # 2.33.0
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Load ECS Cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: /tmp/ecs
          key: ${{ runner.os }}-ecs-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-ecs-${{ github.run_id }}

      - name: Create cache directory
        run: mkdir -p /tmp/ecs

      - name: Run ECS
        run: ./vendor/bin/ecs --config=ecs.php check

  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # 2.33.0
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Update dependencies with composer
        run: composer update --no-interaction --no-ansi --no-progress

      - name: Load Rector Cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: /tmp/rector
          key: ${{ runner.os }}-rector-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-rector-${{ github.run_id }}

      - name: Create cache directory
        run: mkdir -p /tmp/rector

      - name: Run Rector
        run: ./vendor/bin/rector --config=rector.php process --dry-run

      - name: Checkout GitHub action code to be correctly deleted in the post step
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: '.github/actions/setup-plugin'
          sparse-checkout-cone-mode: false

  static-analysis:
    name: Static analysis (PHPStan)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']
        shopware-version: ['v6.5.7.4', 'v6.5.8.17']
    steps:
      - name: Checkout GitHub action code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: '.github/actions/setup-plugin'
          sparse-checkout-cone-mode: false

      - name: Setup Shopware and Plugin
        uses: ./.github/actions/setup-plugin
        with:
          shopware-version: ${{ matrix.shopware-version }}
          php-version: ${{ matrix.php-version }}

      - name: Run PHPStan
        working-directory: 'custom/plugins/ITBConfigurableListingFilters'
        run: |
          rm -rf phpstan-ci.neon
          composer dump-autoload --dev
          composer run static-analysis-ci

      - name: Checkout GitHub action code to be correctly deleted in the post step
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: '.github/actions/setup-plugin'
          sparse-checkout-cone-mode: false
