name: Test Code

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  phpunit-unit-tests:
    name: PHPUnit unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']
        shopware-version: ['v6.5.7.4', 'v6.5.8.17']
    steps:
      - name: Checkout GitHub action code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: '.github/actions/setup-plugin'
          sparse-checkout-cone-mode: false

      - name: Setup Shopware and Plugin
        uses: ./.github/actions/setup-plugin
        with:
          shopware-version: ${{ matrix.shopware-version }}
          php-version: ${{ matrix.php-version }}
          install-phpunit: 'true'

      - name: Run PHPUnit
        working-directory: 'custom/plugins/ITBConfigurableListingFilters'
        run: |
          composer dump-autoload --dev
          php ${GITHUB_WORKSPACE}/vendor/bin/phpunit \
            --configuration phpunit.xml.dist \
            --testsuite 'unit tests'

      - name: Checkout GitHub action code to be correctly deleted in the post step
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: '.github/actions/setup-plugin'
          sparse-checkout-cone-mode: false

  phpunit-integration-tests:
    name: PHPUnit integration tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']
        shopware-version: ['v6.5.7.4', 'v6.5.8.17']
    steps:
      - name: Checkout GitHub action code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: '.github/actions/setup-plugin'
          sparse-checkout-cone-mode: false

      - name: Setup Shopware and Plugin
        uses: ./.github/actions/setup-plugin
        with:
          shopware-version: ${{ matrix.shopware-version }}
          php-version: ${{ matrix.php-version }}
          install-phpunit: 'true'

      - name: Run PHPUnit
        working-directory: 'custom/plugins/ITBConfigurableListingFilters'
        run: |
          composer dump-autoload --dev
          php ${GITHUB_WORKSPACE}/vendor/bin/phpunit \
            --configuration phpunit.xml.dist \
            --testsuite 'integration tests'

      - name: Checkout GitHub action code to be correctly deleted in the post step
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: '.github/actions/setup-plugin'
          sparse-checkout-cone-mode: false
